quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('leaderboard/', views.leaderboard_view, name='leaderboard'),
    path('quiz/', views.quiz_view, name='quiz'),

    path('api/quiz/create', views.get_quiz, name='get_quiz'),
    path('api/quiz/<str:quiz_id>/result', views.get_result, name='get_result'),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    username = models.CharField(max_length=32, unique=True)
    score = models.IntegerField(default=0)
    life = models.IntegerField(default=3)
    highest_record = models.IntegerField(default=0)
    highest_record_at = models.DateTimeField(null=True)

    def __str__(self):
        return self.username


class Movie(models.Model):
    title = models.TextField()

    def __str__(self):
        return self.title


class Prompt(models.Model):
    type = models.CharField(max_length=16)
    prompt = models.TextField()

    def __str__(self):
        return f"Type: {self.type}, Prompt: {self.prompt[:25]}"


class Quiz(models.Model):
    id = models.CharField(primary_key=True, default='00000000', max_length=8, editable=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='movie_titles')
    question = models.TextField()
    option_a = models.TextField()
    option_b = models.TextField()
    option_c = models.TextField()
    option_d = models.TextField()
    answer = models.CharField(max_length=1)
    explanation = models.TextField()
    imdb_url = models.URLField()

    def __str__(self):
        return f"[{self.id}] {self.question[:50]}"


class Result(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quiz_results')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='user_results')
    is_choice_correct = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    feedback = models.TextField(null=True, blank=False)

    class Meta:
        unique_together = ('user', 'quiz')

    def __str__(self):
        return f"{self.user.username}'s result on quiz [{self.quiz.id}]"

quiz/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

quiz/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.db.models.expressions import Window
from django.db.models.functions import Rank
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.decorators.csrf import ensure_csrf_cookie

import environ
import io
import json
import openai
import os
import re
import string

from google.cloud import secretmanager
from secrets import choice, randbelow
from supabase import create_client
from tenacity import retry, stop_after_attempt, wait_random_exponential

from .models import User, Quiz, Prompt, Movie


# Set environment variables
env = environ.Env(DEBUG=(bool, False))
env_file = os.path.join(settings.BASE_DIR, 'KinoQuizAI', '.env')

# Read a local .env file
if os.path.isfile(env_file):
    env.read_env(env_file)

# Pull .env file from GCP Secret Manager
elif os.environ.get('GOOGLE_CLOUD_PROJECT', None):
    project_id = os.environ.get('GOOGLE_CLOUD_PROJECT')
    client = secretmanager.SecretManagerServiceClient()
    settings_name = os.environ.get('SETTINGS_NAME', 'django_settings')
    name = f'projects/{project_id}/secrets/{settings_name}/versions/latest'
    payload = client.access_secret_version(name=name).payload.data.decode('UTF-8')

    env.read_env(io.StringIO(payload))

# Neither option is available, raise exception
else:
    raise Exception('No local .env or GOOGLE_CLOUD_PROJECT detected. No secrets found.')


def home_view(request):
    return render(request, "home.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            next_path = request.POST.get("next") or None
            if next_path:
                return redirect(next_path)
            return redirect("quiz:home")
        else:
            return render(request, "login.html", {
                "message": "Invalid username and/or password."
            })

    else:
        next_path = request.GET.get("next") or request.META.get("HTTP_REFERER")
        return render(request, "login.html", {
            "next": next_path
        })


def logout_view(request):
    if not request.user.is_authenticated:
        return redirect("quiz:home")
    logout(request)
    return redirect(request.path)


def register_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "register.html", {
                "message": "Passwords must match."
            })

        # Allow only up to 16 alphanumeric + hyphen + underscore characters to username
        if not (re.match(r"^[A-Za-z0-9_-]+$", username) and len(username) <= 16):
            return render(request, "register.html", {
                "message": "Only up to 16 alphanumeric characters, hyphen and underscore are allowed to username."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username=username, password=password)
            user.save()
        except IntegrityError:
            return render(request, "register.html", {
                "message": "Username already taken."
            })

        # After creating new user, allow login to the app and redirect to home
        login(request, user)
        return redirect("quiz:home")

    else:
        return render(request, "register.html")


@login_required
def quiz_view(request):
    user = get_object_or_404(User, id=request.user.id)

    # Reset user's current score and life everytime when user starts playing
    user.score = 0
    user.life = 3
    user.save()

    return render(request, "quiz.html", {
        "user": user
    })


def leaderboard_view(request):
    all_users_by_ranking = User.objects.filter(highest_record__gt=0)\
        .annotate(rank=Window(expression=Rank(), order_by="-highest_record"))
    top_10_users = all_users_by_ranking[:10]

    try:
        user = User.objects.get(id=request.user.id)
        # Currently filtering against window function doesn't keep the values annotated in the queryset.
        # In the upcoming Django 4.2, filtering against window functions will be available
        # which likely makes the task finding user's current rank more efficient.
        # https://github.com/django/django/pull/15922
        # https://github.com/django/django/blob/main/docs/releases/4.2.txt
        user_rank = 0
        for user_by_ranking in all_users_by_ranking:
            if user_by_ranking.id == user.id:
                user_rank = user_by_ranking.rank
    except User.DoesNotExist:
        user = user_rank = None

    if request.user.is_authenticated and user and user_rank:
        return render(request, "leaderboard.html", {
            "user": user,
            "user_rank": user_rank,
            "top_10_users": top_10_users
        })

    return render(request, "leaderboard.html", {
        "top_10_users": top_10_users
    })


def get_prompt_data():

    # Get a movie title to make a question
    movies = Movie.objects.all()
    movies_count = movies.count()
    if movies_count > 0:
        movie = movies[randbelow(movies_count)]
    else:
        movie = set_prompt(type="movie")

    # Get a text contain conditions to make a request
    try:
        conditions = Prompt.objects.get(type="condition").prompt
    except Prompt.DoesNotExist:
        conditions = set_prompt(type="condition")

    # To produce the data in the desired format or topic, add a random sample quiz template as an example
    samples = Prompt.objects.filter(type="sample")
    if samples.count() > 0:
        sample = samples[randbelow(samples.count())].prompt
    else:
        sample = set_prompt(type="sample")

    # If there was a problem retrieving prompts, return None
    if not (movie or conditions or sample):
        print(f"There was a problem during retrieving prompt data:\n")
        print(f"Title: {movie.title}\nConditions: {conditions}\nSample: {sample}")
        return None

    # Combine templates to generate the prompt to get a new quiz from Completions/Chat API
    result = {
        "prompt": f"CREATE A SINGLE QUIZ WITH FOUR OPTIONS ABOUT MOVIE '{movie.title}'.\n" + conditions + "\n\n" + sample + "\n\n[Question]",
        "movie_id": movie.id
    }
    return result


def set_prompt(type):

    print(f"Initializing '{type}' data to generate prompts...")

    # Connect to Supabase Storage
    url = env("SUPABASE_URL")
    key = env("SUPABASE_ANON_KEY")
    client = create_client(url, key)
    bucket = client.storage.get_bucket(env("SUPABASE_BUCKET_PROMPTS"))

    # Get the movie title
    if type == "movie":

        prompt_movie_file = bucket.download("movies.txt")
        prompt_movie_content = prompt_movie_file.decode("utf-8")

        prompt_movie_titles = [title for title in prompt_movie_content.splitlines() if title]
        for title in prompt_movie_titles:
            prompt_movie = Movie(
                title=title
            )
            prompt_movie.save()

        prompt_movies = Movie.objects.all()
        return prompt_movies[randbelow(prompt_movies.count())]


    # Get the condition prompt
    if type == "condition":

        prompt_condition_file = bucket.download("conditions.txt")
        prompt_condition_content = prompt_condition_file.decode("utf-8")
        prompt_condition = Prompt(
            type="condition",
            prompt=prompt_condition_content
        )
        prompt_condition.save()

        return prompt_condition_content

    # Get the sample question prompts
    if type == "sample":

        prompt_sample_files = bucket.list("samples/")

        for filename in prompt_sample_files:
            prompt_sample_file = bucket.download(f"samples/{filename['name']}")
            prompt_sample_content = prompt_sample_file.decode("utf-8")
            prompt_sample = Prompt(
                type="sample",
                prompt=prompt_sample_content
            )
            prompt_sample.save()

        prompt_samples = Prompt.objects.filter(type="sample")
        return prompt_samples[randbelow(prompt_samples.count())].prompt

    return None


@retry(wait=wait_random_exponential(min=1, max=60), stop=stop_after_attempt(5), reraise=True)
def get_response_from_gpt(prompt, chatapi=True):

    if not prompt:
        print("There was a problem retrieving the prompt. Aborted the process.")
        return None

    openai.organization = env("OPENAI_ORGANIZATION")
    openai.api_key = env("OPENAI_API_KEY")

    # Preset the parameters for Completions/Chat API
    # To check descriptions for each parameter, visit https://platform.openai.com/docs/api-reference/completions
    parameters = {
        "temperature": 1.15,
        "top_p": 0.7,
        "frequency_penalty": 1,
        "presence_penalty": 0.85,
        "max_tokens": 2048
    }

    print("Start getting a response from OpenAI API...")

    try:
        # If chatapi is True, use ChatCompletion mode with gpt-3.5-turbo model
        if chatapi:
            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {
                        "role": "system",
                        "content": "Suppose you are an examiner in the movie lecture class."
                    },
                    {
                        "role": "user",

quiz/templates/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" class="bg-base-bg" style="-moz-text-size-adjust: none; -webkit-text-size-adjust: none; text-size-adjust: none;">

<head>
  <title>{% block title %}KinoQuizAI{% endblock %}</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, minimal-ui, viewport-fit=cover, initial-scale=1.0">
  <meta name="theme-color" content="#061012">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% tailwind_css %}
  <script>
    let vh = window.innerHeight * 0.01;
    document.documentElement.style.setProperty('--vh', `${vh}px`);
  </script>
  <style>
    body {
      padding-left: env(safe-area-inset-left);
      padding-right: env(safe-area-inset-right);
    }
    #home-container {
      min-height: calc(var(--vh, 1vh) * 100 - 8rem);
    }
    .min-safe-h-screen {
      min-height: calc(var(--vh, 1vh) * 100);
    }
  </style>
  <link rel="canonical" href="https://kinoquiz.app/">
  <meta property="og:site_name" content="KinoQuizAI">
  <meta property="og:type" content="website">
  <meta property="og:title" content="KinoQuizAI">
  <meta property="og:description" content="KinoQuizAI is an ChatGPT powered movie quiz game that lets you compete with others while testing your movie knowledge.">
  <meta property="og:url" content="https://kinoquiz.app/">
  <meta property="og:image" content="{% static 'img/og_image.jpg' %}">
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-JC6ZM5P5C3"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-JC6ZM5P5C3');
  </script>
</head>

<link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.png' %}">
<link rel="manifest" href="{% static 'icons/site.webmanifest' %}">

<body class="bg-base-bg bg-image bg-cover bg-bottom min-safe-h-screen">

{% block nav %}
  {% include 'navigation.html' %}
{% endblock %}

{% block body %}
{% endblock %}

</body>

{% block script %}
{% endblock %}

</html>

quiz/templates/footer.html
{% load static %}

<footer class="relative w-full py-5" style="margin-bottom: env(safe-area-inset-bottom)">
  <div class="text-slate-50 text-sm text-center font-light">
    Copyright © 2023 by
    <a href="https://seongjin.me" target="_blank" class="inline-block align-bottom ml-1"><img src="{% static 'img/icon_seongjin.me.png' %}" class="w-5 h-5"></a>
  </div>
</footer>

quiz/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
  <div id="home-container" class="relative flex px-6 py-10 justify-center items-center">
    <div id="home-introduction" class="max-w-lg text-center">
      <h1 class="transition-opacity text-white text-4xl sm:text-5xl font-bold drop-shadow-md">KinoQuizAI 💫️</h1>
      <p class="text-slate-100 text-base sm:text-xl mt-7 font-light">KinoQuizAI is an ChatGPT powered movie quiz game that lets you compete with others while testing your movie knowledge.</p>
      <p class="inline-block text-slate-50 text-sm mt-6 font-medium rounded-lg px-3 py-2 bg-black/50">Think You Know Movies? Prove It!</p>
      <div class="mt-10">
        <a href="{% url 'quiz:quiz' %}" class="inline-block text-white font-semibold px-7 py-4 rounded-lg bg-gradient-to-r from-teal-500 to-blue-500 hover:scale-110 focus:scale-110 drop-shadow-md ease-in-out duration-300">
          GET STARTED
        </a>
      </div>
    </div>
  </div>

  {% include 'footer.html' %}

{% endblock %}

{% block script %}
{% endblock %}

quiz/templates/leaderboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Leaderboard - KinoQuizAI{% endblock %}

{% block body %}
  <div id="leaderboard-container" class="flex items-center justify-center py-8 sm:py-12 px-6">
    <div class="w-full max-w-lg space-y-6 sm:space-y-8">

      {% if error or message %}
        <div class="bg-rose-100 px-3 py-4 border-2 border-rose-500 drop-shadow-lg rounded-lg">
          <p class="text-center text-sm text-rose-600">
            {{ error }}
            {{ message }}
          </p>
        </div>
      {% endif %}

      <div id="quiz-card" class="bg-neutral-100 space-y-6 sm:space-y-8 p-6 sm:p-8 drop-shadow-lg rounded-lg">
        <h2 class="text-center text-2xl sm:text-3xl font-bold tracking-tight text-gray-900">
          Leaderboard
        </h2>

        <div id="leaderboard-description">
          <p class="text-sm sm:text-base">Here are top 10 users who have aced the quizzes and earned the most points. Challenge them and climb to the top!</p>
        </div>

        {% if user_rank %}
        <div id="leaderboard-user-status">
          <p class="text-sm text-slate-400 mb-2">Your place with highest record:</p>
          <div id="leaderboard-user-place" class="p-3 sm:p-4 w-full h-full bg-blue-50 border-2 border-blue-400 text-blue-600 rounded-md drop-shadow-sm">
            <div class="flex items-center h-12 justify-between">
              <div class="w-5/6">
                <div class="inline-block min-w-[1.25rem] sm:min-w-[1.75rem] text-lg text-blue-600 tracking-tighter sm:text-2xl font-bold align-middle">{{ user_rank }}</div>
                <div class="inline-block align-middle ml-2 sm:ml-3">
                  <p class="text-base sm:text-lg text-blue-600 font-semibold">{{ user.username }}</p>
                  <p class="text-[0.65rem] font-normal text-slate-400 tracking-tight sm:tracking-normal">Updated: {{ user.highest_record_at|date:'Y-m-d' }} {{ user.highest_record_at|time:'P' }}</p>
                </div>
              </div>
              <div class="w-1/6 text-right text-blue-600 text-sm tracking-tighter sm:tracking-normal">
                <span class="text-lg font-bold sm:text-2xl">{{ user.highest_record }}</span> pts
              </div>
            </div>
          </div>
        </div>
        {% endif %}

        <div id="leaderboard-top-10">
          <p class="text-sm text-slate-400 mb-2">Top users in KinoQuizAI:</p>
          <div id="leaderboard-top-10-list" class="max-w-md p-4 space-y-4 bg-neutral-50 border border-slate-300 divide-y divide-slate-300 rounded-md drop-shadow-sm">
          {% if top_10_users %}
          {% for top_10_user in top_10_users %}

            {% if forloop.first %}
            <div class="flex items-center h-12 justify-between">
              <div class="w-5/6">
                <div class="inline-block min-w-[1.25rem] sm:min-w-[1.75rem] text-lg text-slate-600 tracking-tighter sm:text-2xl font-bold align-middle">{{ top_10_user.rank }}</div>
                <div class="inline-block align-middle ml-2 sm:ml-3">
                  <p class="text-base sm:text-lg font-semibold text-slate-600">{{ top_10_user.username }} 🥇</p>
                  <p class="text-[0.65rem] font-normal text-slate-400 tracking-tight sm:tracking-normal">Updated: {{ top_10_user.highest_record_at|date:'Y-m-d' }} {{ top_10_user.highest_record_at|time:'P' }}</p>
                </div>
              </div>
              <div class="w-1/6 text-right text-slate-600 text-sm tracking-tighter sm:tracking-normal">
                <span class="text-lg font-bold sm:text-2xl">{{ top_10_user.highest_record }}</span> pts
              </div>
            </div>
            {% elif forloop.counter == 2 %}
            <div class="flex items-center h-16 pt-4 justify-between">
              <div class="w-5/6">
                <div class="inline-block min-w-[1.25rem] sm:min-w-[1.75rem] text-lg text-slate-600 tracking-tighter sm:text-2xl font-bold align-middle">{{ top_10_user.rank }}</div>
                <div class="inline-block align-middle ml-2 sm:ml-3">
                  <p class="text-base sm:text-lg font-semibold text-slate-600">{{ top_10_user.username }} 🥈</p>
                  <p class="text-[0.65rem] font-normal text-slate-400 tracking-tight sm:tracking-normal">Updated: {{ top_10_user.highest_record_at|date:'Y-m-d' }} {{ top_10_user.highest_record_at|time:'P' }}</p>
                </div>
              </div>
              <div class="w-1/6 text-right text-slate-600 text-sm tracking-tighter sm:tracking-normal">
                <span class="text-lg font-bold sm:text-2xl">{{ top_10_user.highest_record }}</span> pts
              </div>
            </div>
            {% elif forloop.counter == 3 %}
            <div class="flex items-center h-16 pt-4 justify-between">
              <div class="w-5/6">
                <div class="inline-block min-w-[1.25rem] sm:min-w-[1.75rem] text-lg text-slate-600 tracking-tighter sm:text-2xl font-bold align-middle">{{ top_10_user.rank }}</div>
                <div class="inline-block align-middle ml-2 sm:ml-3">
                  <p class="text-base sm:text-lg font-semibold text-slate-600">{{ top_10_user.username }} 🥉</p>
                  <p class="text-[0.65rem] font-normal text-slate-400 tracking-tight sm:tracking-normal">Updated: {{ top_10_user.highest_record_at|date:'Y-m-d' }} {{ top_10_user.highest_record_at|time:'P' }}</p>
                </div>
              </div>
              <div class="w-1/6 text-right text-slate-600 text-sm tracking-tighter sm:tracking-normal">
                <span class="text-lg font-bold sm:text-2xl">{{ top_10_user.highest_record }}</span> pts
              </div>
            </div>
            {% else %}
            <div class="flex items-center h-16 pt-4 justify-between">
              <div class="w-5/6">
                <div class="inline-block min-w-[1.25rem] sm:min-w-[1.75rem] text-lg text-slate-600 tracking-tighter sm:text-2xl font-bold align-middle">{{ top_10_user.rank }}</div>
                <div class="inline-block align-middle ml-2 sm:ml-3">
                  <p class="text-base sm:text-lg font-semibold text-slate-600">{{ top_10_user.username }}</p>
                  <p class="text-[0.65rem] font-normal text-slate-400 tracking-tight sm:tracking-normal">Updated: {{ top_10_user.highest_record_at|date:'Y-m-d' }} {{ top_10_user.highest_record_at|time:'P' }}</p>
                </div>
              </div>
              <div class="w-1/6 text-right text-slate-600 text-sm tracking-tighter sm:tracking-normal">
                <span class="text-lg font-bold sm:text-2xl">{{ top_10_user.highest_record }}</span> pts
              </div>
            </div>
            {% endif %}
          {% endfor %}
          {% endif %}
          </div>
        </div>

        <div class="text-center h-full">
          <a type="button" id="back-to-main-button"
            class="block rounded-md py-3 px-4 text-white font-semibold bg-gradient-to-r from-teal-500 to-blue-500 hover:scale-105 focus:scale-105 drop-shadow-sm ease-in-out duration-300"
            href="/">
            Back to Home
          </a>
        </div>

      </div>
    </div>
  </div>
{% endblock %}

quiz/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login - KinoQuizAI{% endblock %}

{% block body %}
  <div id="login-container" class="flex items-center justify-center py-8 sm:py-12 px-6">

    <div class="max-w-lg space-y-4">
      {% if message %}
        <div class="bg-rose-100 px-3 py-4 border-2 border-rose-500 drop-shadow-lg rounded-lg">
          <p class="text-center text-sm text-rose-600">
            {{ message }}
          </p>
        </div>
      {% endif %}

      <div class="bg-neutral-100 px-6 py-8 sm:px-9 sm:py-12 drop-shadow-lg rounded-lg">
        <h2 class="text-center text-2xl sm:text-3xl font-bold tracking-tight text-gray-900">
          Log in to account
        </h2>
        <form class="mt-4 sm:mt-8 space-y-6 text-center" method="post" action="{% url 'quiz:login' %}">
          {% csrf_token %}
          <div class="-space-y-px rounded-md drop-shadow-sm">
            <label class="sr-only" for="username">Username</label>
            <input autofocus class="relative block w-full rounded-t-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-blue-600 sm:leading-6" type="text" id="username" name="username" placeholder="Username" maxlength="16" autocomplete="off">
            <label class="sr-only" for="password">Password</label>
            <input class="relative block w-full rounded-b-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-blue-600 sm:leading-6" type="password" id="password" name="password" placeholder="Password" autocomplete="off">
            {% if next %}<input type="hidden" name="next" value="{{ next }}">{% endif %}
          </div>
          <button type="submit" class="group relative flex w-full justify-center rounded-md py-2.5 px-3 font-bold text-white bg-gradient-to-r from-teal-500 to-blue-500 hover:scale-105 focus:scale-105 drop-shadow-sm ease-in-out duration-300">Log in</button>
          <p>Don't have an account? <a href="{% url 'quiz:register' %}" class="inline-block text-blue-500 hover:text-blue-400 focus:text-blue-400">Register here.</a></p>
        </form>
      </div>

    </div>

{% endblock %}

quiz/templates/navigation.html
<nav class="bg-base-bg w-full" style="padding-left: env(safe-area-inset-left); padding-right: env(safe-area-inset-right);">
  <div class="mx-auto max-w-6xl px-3">
    <div class="flex h-14 items-center justify-between">
      <div class="flex flex-1 items-center">
        <div class="flex flex-shrink-0 items-center">
          <a class="text-2xl font-bold rounded-md px-3 py-1 hover:hover:bg-slate-50/10" href="{% url 'quiz:home' %}">
            💫
          </a>
        </div>
      </div>
      <div class="flex-none">
        <a href="{% url 'quiz:leaderboard' %}" class="text-slate-50 hover:bg-slate-50/10 rounded-md px-2 py-2 text-sm font-light">Leaderboard</a>
        {% if user.is_authenticated %}
          <a href="{% url 'quiz:logout' %}" class="text-slate-50 hover:bg-slate-50/10 rounded-md px-2 py-2 text-sm font-light">Logout</a>
        {% else %}
          <a href="{% url 'quiz:login' %}" class="text-slate-50 hover:bg-slate-50/10 rounded-md px-2 py-2 text-sm font-light">Login</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

quiz/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Register - KinoQuizAI{% endblock %}

{% block body %}
  <div id="login-container" class="flex items-center justify-center py-8 sm:py-12 px-6">

    <div class="max-w-lg space-y-4">
      {% if message %}
        <div class="bg-rose-100 px-3 py-4 border-2 border-rose-500 drop-shadow-lg rounded-lg">
          <p class="text-center text-sm text-rose-600">
            {{ message }}
          </p>
        </div>
      {% endif %}

      <div class="bg-neutral-100 px-6 py-8 sm:px-9 sm:py-12 drop-shadow-lg rounded-lg">
        <h2 class="text-center text-2xl sm:text-3xl font-bold tracking-tight text-gray-900">
          Register your account
        </h2>
        <form class="mt-4 sm:mt-8 space-y-6 text-center" method="post" action="{% url 'quiz:register' %}">
          {% csrf_token %}
          <div class="-space-y-px rounded-md drop-shadow-sm">
            <label class="sr-only" for="username">Username</label>
            <input autofocus class="relative block w-full rounded-t-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-blue-600 sm:leading-6" type="text" id="username" name="username" placeholder="Username" maxlength="16" autocomplete="off">
            <label class="sr-only" for="password">Password</label>
            <input class="relative block w-full border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-blue-600 sm:leading-6" type="password" id="password" name="password" placeholder="Password" autocomplete="off">
            <label class="sr-only" for="confirmation">Confirm Password</label>
            <input class="relative block w-full rounded-b-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-blue-600 sm:leading-6" type="password" id="confirmation" name="confirmation" placeholder="Confirm Password" autocomplete="off">
          </div>
          <button type="submit" class="group relative flex w-full justify-center rounded-md py-2.5 px-3 font-bold text-white bg-gradient-to-r from-teal-500 to-blue-500 hover:scale-105 focus:scale-105 drop-shadow-sm ease-in-out duration-300">Register</button>
          <p>Already have an account? <a href="{% url 'quiz:login' %}" class="inline-block text-blue-500 hover:text-blue-400 focus:text-blue-400">Log in here.</a></p>
        </form>
      </div>

    </div>

{% endblock %}